# Generated by Django 4.2.3 on 2023-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Six Months", "Six Months"),
                    ("Three Months", "Three Months"),
                ],
                max_length=15,
            ),
        ),
    ]
